In [24]:
import pandas as pd


df = pd.read_csv("data/investments.csv")# Daten aus CSV laden
df

   client_id client_name        date asset  amount  buy_price_usd
0          1        Anna  2025-01-10   BTC    0.05          42000
1          2        Mark  2025-02-15   BTC    0.02          45000
2          1        Anna  2025-03-01   BTC    0.03          46000
3          3       Julia  2025-02-20   BTC    0.01          47000

In [25]:
from etl.extract import get_bitcoin_price
from etl.transform import transform_data, calculate_profit

price = get_bitcoin_price() # Bitcoin Preis von API holen

df = transform_data(df)     # Daten vorbereiten
df = calculate_profit(df, price)    # Gewinn berechnen

df      # Ergebnis anzeigen

,client_id,client_name,date,asset,amount,buy_price_usd,current_value,buy_value,profit
0,1,Anna,2025-01-10,BTC,0.05,42000,3312.5,2100.0,1212.5
1,2,Mark,2025-02-15,BTC,0.02,45000,1325.0,900.0,425.0
2,1,Anna,2025-03-01,BTC,0.03,46000,1987.5,1380.0,607.5
3,3,Julia,2025-02-20,BTC,0.01,47000,662.5,470.0,192.5

In [26]:
df.groupby("client_name")["profit"].sum() # Gewinn pro Kunde berechnen

client_name
Anna     1820.0
Julia     192.5
Mark      425.0
Name: profit, dtype: float64

In [27]:
df.groupby("client_name")["profit"].mean()

client_name
Anna     910.0
Julia    192.5
Mark     425.0
Name: profit, dtype: float64

In [32]:
df.groupby("client_name")["profit"].sum().sort_values(ascending=True)

client_name
Julia     192.5
Mark      425.0
Anna     1820.0
Name: profit, dtype: float64