In [66]:
from matplotlib.backend_bases import cursors

from db.db_connection import create_connection
import pandas as pd
from utils.formatter import prettify
import warnings
warnings.filterwarnings("ignore")
connection = create_connection()

query = """SELECT * FROM v_transactions_overview"""
df = pd.read_sql(query, connection)
prettify(df)

,ID,Customer,Platform,Asset,status,currency,Date,Amount,Buy Price,Buy Price (EUR),Exchange Fee,Service Fee,Referral Bonus
0,4,Anna,Binance,ETH,completed,USD,2025-04-14,0.0229,1608.28,1413.63,6.86,3.19,1.01
1,15,Lisa,Binance,ETH,completed,USD,2025-05-06,0.2114,1824.89,1611.38,9.93,2.91,1.87
2,26,Tom,Binance,ETH,completed,USD,2025-05-23,0.0746,2682.63,2373.81,6.53,3.84,2.82
3,34,Anna,Binance,ETH,completed,USD,2025-06-05,0.0132,2584.92,2262.92,7.31,4.24,0.10
4,48,Anna,Binance,ETH,completed,USD,2025-06-26,0.3414,2426.10,2074.48,9.41,2.55,1.79
...,...,...,...,...,...,...,...,...,...,...,...,...,...
222,178,Lisa,Kraken,BTC,completed,USD,2026-02-10,0.0194,69912.69,58779.79,8.43,1.38,0.52
223,185,Mark,Kraken,BTC,completed,USD,2026-02-22,0.0231,67429.85,57303.91,8.97,3.83,2.33
224,191,Julia,Kraken,BTC,pending,USD,2026-03-05,0.0443,72256.16,62193.05,8.27,4.71,1.31
225,194,Tom,Kraken,BTC,completed,USD,2026-03-10,0.0498,68860.12,59152.90,6.57,2.69,0.85
226,216,Lisa,Kraken,BTC,pending,USD,2026-04-06,0.0486,67609.50,58663.41,7.10,4.42,0.78

In [46]:
query = """
SELECT * FROM market_prices
ORDER BY price_id DESC, price_date DESC

LIMIT 10"""
df = pd.read_sql(query, connection)
df

,price_id,asset_id,price_date,price_eur,created_at,updated_at,price_usd,eur_rate
0,728,2,2026-04-06 00:18:04,1781.815587,2026-04-06 00:18:04,2026-04-06 00:18:04,2053.54,0.86768
1,727,1,2026-04-06 00:18:04,58564.061600,2026-04-06 00:18:04,2026-04-06 00:18:04,67495.00,0.86768
2,726,2,2026-04-06 00:17:29,1781.815587,2026-04-06 00:17:29,2026-04-06 00:17:29,2053.54,0.86768
3,725,1,2026-04-06 00:17:29,58564.061600,2026-04-06 00:17:29,2026-04-06 00:17:29,67495.00,0.86768
4,724,2,2026-04-06 00:08:20,1791.871998,2026-04-06 00:08:21,2026-04-06 00:08:21,2065.13,0.86768
5,723,1,2026-04-06 00:08:20,58711.567200,2026-04-06 00:08:21,2026-04-06 00:08:21,67665.00,0.86768
6,722,2,2026-04-06 00:07:04,1791.733170,2026-04-06 00:07:04,2026-04-06 00:07:04,2064.97,0.86768
7,721,1,2026-04-06 00:07:04,58696.816640,2026-04-06 00:07:04,2026-04-06 00:07:04,67648.00,0.86768
8,720,2,2026-04-06 00:05:36,1791.429482,2026-04-06 00:05:36,2026-04-06 00:05:36,2064.62,0.86768
9,719,1,2026-04-06 00:05:36,58679.463040,2026-04-06 00:05:36,2026-04-06 00:05:36,67628.00,0.86768

In [67]:
query = """
SELECT * FROM market_prices WHERE DATE(price_date) = CURDATE()"""
df = pd.read_sql(query, connection)
df

,price_id,asset_id,price_date,price_eur,created_at,updated_at,price_usd,eur_rate
0,719,1,2026-04-06 00:05:36,58679.463040,2026-04-06 00:05:36,2026-04-06 00:05:36,67628.00,0.86768
1,720,2,2026-04-06 00:05:36,1791.429482,2026-04-06 00:05:36,2026-04-06 00:05:36,2064.62,0.86768
2,721,1,2026-04-06 00:07:04,58696.816640,2026-04-06 00:07:04,2026-04-06 00:07:04,67648.00,0.86768
3,722,2,2026-04-06 00:07:04,1791.733170,2026-04-06 00:07:04,2026-04-06 00:07:04,2064.97,0.86768
4,723,1,2026-04-06 00:08:20,58711.567200,2026-04-06 00:08:21,2026-04-06 00:08:21,67665.00,0.86768
5,724,2,2026-04-06 00:08:20,1791.871998,2026-04-06 00:08:21,2026-04-06 00:08:21,2065.13,0.86768
6,725,1,2026-04-06 00:17:29,58564.061600,2026-04-06 00:17:29,2026-04-06 00:17:29,67495.00,0.86768
7,726,2,2026-04-06 00:17:29,1781.815587,2026-04-06 00:17:29,2026-04-06 00:17:29,2053.54,0.86768
8,727,1,2026-04-06 00:18:04,58564.061600,2026-04-06 00:18:04,2026-04-06 00:18:04,67495.00,0.86768
9,728,2,2026-04-06 00:18:04,1781.815587,2026-04-06 00:18:04,2026-04-06 00:18:04,2053.54,0.86768
10,729,1,2026-04-06 00:21:06,58629.137600,2026-04-06 00:21:07,2026-04-06 00:21:07,67570.00,0.86768
11,730,2,2026-04-06 00:21:06,1783.819928,2026-04-06 00:21:07,2026-04-06 00:21:07,2055.85,0.86768
12,731,1,2026-04-06 00:21:44,58588.356640,2026-04-06 00:21:44,2026-04-06 00:21:44,67523.00,0.86768
13,732,2,2026-04-06 00:21:44,1782.891510,2026-04-06 00:21:44,2026-04-06 00:21:44,2054.78,0.86768
14,733,1,2026-04-06 00:25:00,58476.425920,2026-04-06 00:25:00,2026-04-06 00:25:00,67394.00,0.86768
15,734,2,2026-04-06 00:25:00,1779.845954,2026-04-06 00:25:00,2026-04-06 00:25:00,2051.27,0.86768
16,735,1,2026-04-06 00:28:13,58472.955200,2026-04-06 00:28:13,2026-04-06 00:28:13,67390.00,0.86768
17,736,2,2026-04-06 00:28:13,1780.045520,2026-04-06 00:28:13,2026-04-06 00:28:13,2051.50,0.86768

In [68]:
query="""SELECT * FROM transactions
WHERE DATE (transaction_date)= CURDATE()
ORDER BY transaction_id DESC"""
df = pd.read_sql(query, connection)
df

,transaction_id,client_id,platform_id,asset_id,status_id,transaction_date,amount,buy_price,currency_id,buy_price_eur,exchange_fee_eur,service_fee_eur,referral_bonus_eur,created_at,updated_at,transaction_type
0,227,5,3,2,2,2026-04-06,0.4983,2071.35,1,1797.27,7.12,3.65,0.66,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY
1,226,4,2,1,2,2026-04-06,0.0387,67893.37,1,58909.72,2.25,4.97,1.33,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY
2,225,6,2,2,1,2026-04-06,0.0905,2031.11,1,1762.35,3.04,3.81,0.38,2026-04-06 00:28:13,2026-04-06 00:28:13,SELL
3,224,1,2,1,1,2026-04-06,0.0499,67563.57,1,58623.56,4.36,4.97,2.39,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY
4,223,2,2,2,1,2026-04-06,0.3957,2062.91,1,1789.94,6.79,3.01,0.18,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY
5,222,5,2,1,2,2026-04-06,0.0144,67028.70,1,58159.46,9.13,2.55,2.77,2026-04-06 00:28:13,2026-04-06 00:28:13,SELL
6,221,1,3,2,1,2026-04-06,0.4312,2070.64,1,1796.65,2.54,1.51,1.03,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY
7,220,3,2,1,1,2026-04-06,0.0155,67689.44,1,58732.77,7.47,1.03,0.77,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY
8,219,3,3,2,2,2026-04-06,0.3336,2059.61,1,1787.08,2.38,4.02,1.95,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY
9,218,5,2,1,2,2026-04-06,0.0168,67730.72,1,58768.59,8.20,2.51,1.37,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY
10,217,3,2,2,1,2026-04-06,0.3722,2071.93,1,1797.78,2.60,4.32,2.60,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY
11,216,5,3,1,1,2026-04-06,0.0486,67609.50,1,58663.41,7.10,4.42,0.78,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY
12,215,6,2,2,1,2026-04-06,0.1238,2078.37,1,1803.36,2.28,4.43,0.29,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY
13,214,6,1,1,1,2026-04-06,0.0359,67806.75,1,58834.56,8.11,2.57,1.02,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY
14,213,3,3,2,1,2026-04-06,0.1326,2084.98,1,1809.09,7.71,3.57,1.82,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY
15,212,3,1,1,1,2026-04-06,0.0388,67918.80,1,58931.78,9.22,2.63,0.97,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY
16,211,2,3,2,1,2026-04-06,0.4288,2078.04,1,1803.07,5.95,1.54,0.46,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY
17,210,4,1,1,1,2026-04-06,0.0224,68200.46,1,59176.18,4.40,1.33,1.46,2026-04-06 00:28:13,2026-04-06 00:28:13,BUY