In [26]:
from matplotlib.backend_bases import cursors

from db.db_connection import create_connection
import pandas as pd
from utils.formatter import prettify
import warnings
warnings.filterwarnings("ignore")
connection = create_connection()

query = """SELECT * FROM v_transactions_overview"""
df = pd.read_sql(query, connection)
prettify(df)

,ID,Customer,Platform,Asset,Status,Original Currency,Date,transaction_type,Amount,Buy Price,Buy Price (EUR),Exchange Fee,Service Fee,Referral Bonus
0,4,Tom,Binance,ETH,completed,USD,2025-03-10,BUY,1.2000,2500.00,2350.00,5.00,2.00,0.00
1,10,Mark,Binance,ETH,completed,USD,2025-04-14,BUY,0.0202,1610.28,1415.39,4.89,2.28,1.71
2,14,Tom,Binance,ETH,completed,USD,2025-04-23,BUY,0.0426,1774.23,1554.29,2.77,4.95,0.01
3,29,David,Binance,ETH,pending,USD,2025-05-12,BUY,0.4857,2528.46,2276.65,9.24,3.34,3.00
4,40,Anna,Binance,ETH,completed,USD,2025-05-28,BUY,0.2490,2687.85,2375.07,6.60,4.97,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,196,Julia,Kraken,BTC,completed,USD,2026-03-07,SELL,0.0086,67858.96,58696.64,2.59,2.70,0.00
215,198,Julia,Kraken,BTC,pending,USD,2026-03-08,BUY,0.0392,67854.11,58692.45,3.58,3.28,0.97
216,199,Julia,Kraken,BTC,completed,USD,2026-03-09,SELL,0.0056,65633.02,56800.78,3.92,4.71,2.21
217,207,Tom,Kraken,BTC,completed,USD,2026-03-30,SELL,0.0196,65401.16,56950.02,8.90,1.39,0.59
218,209,Tom,Kraken,BTC,pending,USD,2026-03-31,BUY,0.0412,67158.14,58408.78,3.23,2.29,0.20

In [27]:
def run_query(query):
    connection=create_connection()
    df = pd.read_sql(query, connection)
    connection.close()
    return df

In [28]:
df = run_query("""
SELECT * FROM market_prices WHERE DATE(price_date) = CURDATE()
ORDER BY price_id DESC
LIMIT 10""")
df

,price_id,asset_id,price_date,price_usd,eur_rate,price_eur,created_at,updated_at
0,728,2,2026-04-06 15:21:11,2142.84,0.86768,1859.299411,2026-04-06 15:21:11,2026-04-06 15:21:11
1,727,1,2026-04-06 15:21:11,69360.00,0.86768,60182.284800,2026-04-06 15:21:11,2026-04-06 15:21:11
2,726,2,2026-04-06 12:21:11,2154.71,0.86768,1869.598773,2026-04-06 12:21:12,2026-04-06 12:21:12
3,725,1,2026-04-06 12:21:11,69784.00,0.86768,60550.181120,2026-04-06 12:21:12,2026-04-06 12:21:12
4,724,2,2026-04-06 11:26:10,2166.00,0.86768,1879.394880,2026-04-06 11:26:11,2026-04-06 11:26:11
5,723,1,2026-04-06 11:26:10,70112.00,0.86768,60834.780160,2026-04-06 11:26:11,2026-04-06 11:26:11
6,722,2,2026-04-06 11:25:03,2165.75,0.86768,1879.177960,2026-04-06 11:25:04,2026-04-06 11:25:04
7,721,1,2026-04-06 11:25:03,70105.00,0.86768,60828.706400,2026-04-06 11:25:04,2026-04-06 11:25:04

In [29]:
df = run_query("""
SELECT * FROM market_prices WHERE DATE(price_date) = CURDATE()
ORDER BY price_id DESC
LIMIT 10""")
df

,price_id,asset_id,price_date,price_usd,eur_rate,price_eur,created_at,updated_at
0,730,2,2026-04-06 18:21:14,2162.62,0.86768,1876.462122,2026-04-06 18:21:14,2026-04-06 18:21:14
1,729,1,2026-04-06 18:21:14,69958.00,0.86768,60701.157440,2026-04-06 18:21:14,2026-04-06 18:21:14
2,728,2,2026-04-06 15:21:11,2142.84,0.86768,1859.299411,2026-04-06 15:21:11,2026-04-06 15:21:11
3,727,1,2026-04-06 15:21:11,69360.00,0.86768,60182.284800,2026-04-06 15:21:11,2026-04-06 15:21:11
4,726,2,2026-04-06 12:21:11,2154.71,0.86768,1869.598773,2026-04-06 12:21:12,2026-04-06 12:21:12
5,725,1,2026-04-06 12:21:11,69784.00,0.86768,60550.181120,2026-04-06 12:21:12,2026-04-06 12:21:12
6,724,2,2026-04-06 11:26:10,2166.00,0.86768,1879.394880,2026-04-06 11:26:11,2026-04-06 11:26:11
7,723,1,2026-04-06 11:26:10,70112.00,0.86768,60834.780160,2026-04-06 11:26:11,2026-04-06 11:26:11
8,722,2,2026-04-06 11:25:03,2165.75,0.86768,1879.177960,2026-04-06 11:25:04,2026-04-06 11:25:04
9,721,1,2026-04-06 11:25:03,70105.00,0.86768,60828.706400,2026-04-06 11:25:04,2026-04-06 11:25:04

In [23]:
df = run_query("""SELECT mp.*
FROM market_prices mp
JOIN (
    SELECT asset_id, MAX(price_date) AS max_date
    FROM market_prices
    GROUP BY asset_id
) latest
ON mp.asset_id = latest.asset_id
AND mp.price_date = latest.max_date;""")
df

,price_id,asset_id,price_date,price_usd,eur_rate,price_eur,created_at,updated_at
0,727,1,2026-04-06 15:21:11,69360.00,0.86768,60182.284800,2026-04-06 15:21:11,2026-04-06 15:21:11
1,728,2,2026-04-06 15:21:11,2142.84,0.86768,1859.299411,2026-04-06 15:21:11,2026-04-06 15:21:11

In [7]:
df=run_query("SHOW TABLES")
df

    Tables_in_crypto_portfolio_db
0                       abo_types
1                     asset_types
2                          assets
3                         clients
4                       countries
5                      currencies
6                   market_prices
7                       platforms
8                        statuses
9                    transactions
10  v_market_prices_latest_simple
11     v_portfolio_balance_simple
12       v_portfolio_value_simple
13        v_transactions_overview

In [8]:
df=run_query("DESCRIBE transactions")
df

,Field,Type,Null,Key,Default,Extra
0,transaction_id,int unsigned,NO,PRI,NaN,auto_increment
1,client_id,int unsigned,NO,MUL,NaN,
2,platform_id,int unsigned,NO,MUL,NaN,
3,asset_id,int unsigned,NO,MUL,NaN,
4,status_id,int unsigned,NO,MUL,NaN,
5,transaction_date,date,NO,MUL,NaN,
6,amount,"decimal(18,8)",NO,,NaN,
7,buy_price,"decimal(18,8)",NO,,NaN,
8,currency_id,int unsigned,NO,MUL,NaN,
9,buy_price_eur,"decimal(18,8)",NO,,NaN,
10,exchange_fee_eur,"decimal(18,8)",NO,,0.00000000,
11,service_fee_eur,"decimal(18,8)",NO,,0.00000000,
12,referral_bonus_eur,"decimal(18,8)",NO,,0.00000000,
13,transaction_type,"enum('BUY','SELL')",NO,MUL,BUY,
14,created_at,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED
15,updated_at,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED on update CURRENT_TIMESTAMP

In [9]:
df=run_query("DESCRIBE market_prices")
df

,Field,Type,Null,Key,Default,Extra
0,price_id,int unsigned,NO,PRI,NaN,auto_increment
1,asset_id,int unsigned,NO,MUL,NaN,
2,price_date,datetime,NO,MUL,NaN,
3,price_usd,"decimal(18,2)",YES,,NaN,
4,eur_rate,"decimal(10,6)",YES,,NaN,
5,price_eur,"decimal(18,8)",NO,,NaN,
6,created_at,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED
7,updated_at,timestamp,YES,,CURRENT_TIMESTAMP,DEFAULT_GENERATED on update CURRENT_TIMESTAMP

In [20]:
df = run_query("""SELECT COUNT(*) FROM transactions""")
df

   COUNT(*)
0       215