In [19]:
from matplotlib.backend_bases import cursors

from db.db_connection import create_connection
import pandas as pd
from utils.formatter import prettify
import warnings
warnings.filterwarnings("ignore")

connection = create_connection()

query = """
SELECT * FROM v_transactions_overview
"""

df = pd.read_sql(query, connection)

prettify(df)

,ID,Customer,Platform,Asset,Status,Original Currency,Date,transaction_type,Amount,Buy Price,Buy Price (EUR),Exchange Fee,Service Fee,Referral Bonus
0,4,Tom,Binance,ETH,completed,USD,2025-03-10,BUY,1.2000,2500.00,2350.00,5.00,2.00,0.00
1,10,Mark,Binance,ETH,completed,USD,2025-04-14,BUY,0.0202,1610.28,1415.39,4.89,2.28,1.71
2,14,Tom,Binance,ETH,completed,USD,2025-04-23,BUY,0.0426,1774.23,1554.29,2.77,4.95,0.01
3,29,David,Binance,ETH,pending,USD,2025-05-12,BUY,0.4857,2528.46,2276.65,9.24,3.34,3.00
4,40,Anna,Binance,ETH,completed,USD,2025-05-28,BUY,0.2490,2687.85,2375.07,6.60,4.97,0.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,198,Julia,Kraken,BTC,pending,USD,2026-03-08,BUY,0.0392,67854.11,58692.45,3.58,3.28,0.97
219,199,Julia,Kraken,BTC,completed,USD,2026-03-09,SELL,0.0056,65633.02,56800.78,3.92,4.71,2.21
220,207,Tom,Kraken,BTC,completed,USD,2026-03-30,SELL,0.0196,65401.16,56950.02,8.90,1.39,0.59
221,209,Tom,Kraken,BTC,pending,USD,2026-03-31,BUY,0.0412,67158.14,58408.78,3.23,2.29,0.20
222,220,Mark,Kraken,BTC,pending,USD,2026-04-06,BUY,0.0270,70673.93,61322.36,5.06,4.44,1.27

In [4]:
df["total_buy_eur"] = df["amount"] * df["buy_price_eur"]
prettify(df)

,ID,Customer,Platform,Asset,Status,Original Currency,Date,transaction_type,Amount,Buy Price,Buy Price (EUR),Exchange Fee,Service Fee,Referral Bonus,Total Investment (EUR)
0,4,Tom,Binance,ETH,completed,USD,2025-03-10,BUY,1.2000,2500.00,2350.00,5.00,2.00,0.00,2820.000000
1,10,Mark,Binance,ETH,completed,USD,2025-04-14,BUY,0.0202,1610.28,1415.39,4.89,2.28,1.71,28.590878
2,14,Tom,Binance,ETH,completed,USD,2025-04-23,BUY,0.0426,1774.23,1554.29,2.77,4.95,0.01,66.212754
3,29,David,Binance,ETH,pending,USD,2025-05-12,BUY,0.4857,2528.46,2276.65,9.24,3.34,3.00,1105.768905
4,40,Anna,Binance,ETH,completed,USD,2025-05-28,BUY,0.2490,2687.85,2375.07,6.60,4.97,0.12,591.392430
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,198,Julia,Kraken,BTC,pending,USD,2026-03-08,BUY,0.0392,67854.11,58692.45,3.58,3.28,0.97,2300.744040
219,199,Julia,Kraken,BTC,completed,USD,2026-03-09,SELL,0.0056,65633.02,56800.78,3.92,4.71,2.21,318.084368
220,207,Tom,Kraken,BTC,completed,USD,2026-03-30,SELL,0.0196,65401.16,56950.02,8.90,1.39,0.59,1116.220392
221,209,Tom,Kraken,BTC,pending,USD,2026-03-31,BUY,0.0412,67158.14,58408.78,3.23,2.29,0.20,2406.441736
222,220,Mark,Kraken,BTC,pending,USD,2026-04-06,BUY,0.0270,70673.93,61322.36,5.06,4.44,1.27,1655.703720

In [18]:
market_prices_df = pd.read_sql("SELECT * FROM market_prices", connection)
transactions_df  = pd.read_sql("SELECT * FROM transactions", connection)

market_prices_df.head(10)

,price_id,asset_id,price_date,price_usd,eur_rate,price_eur,created_at,updated_at
0,1,1,2025-04-10,82622.17,0.90236,74554.941588,2026-04-06 11:18:29,2026-04-06 11:18:29
1,2,1,2025-04-11,79596.36,0.88137,70153.841453,2026-04-06 11:18:30,2026-04-06 11:18:30
2,3,1,2025-04-12,83439.29,0.88137,73540.885424,2026-04-06 11:18:30,2026-04-06 11:18:30
3,4,1,2025-04-13,85305.10,0.88137,75185.353593,2026-04-06 11:18:30,2026-04-06 11:18:30
4,5,1,2025-04-14,83600.82,0.87897,73482.612844,2026-04-06 11:18:31,2026-04-06 11:18:31
5,6,1,2025-04-15,84523.45,0.88308,74640.970426,2026-04-06 11:18:31,2026-04-06 11:18:31
6,7,1,2025-04-16,83656.49,0.88067,73673.763240,2026-04-06 11:18:32,2026-04-06 11:18:32
7,8,1,2025-04-17,84105.78,0.88028,74036.635509,2026-04-06 11:18:32,2026-04-06 11:18:32
8,9,1,2025-04-18,84930.91,0.88028,74762.980201,2026-04-06 11:18:32,2026-04-06 11:18:32
9,10,1,2025-04-19,84433.75,0.88028,74325.341602,2026-04-06 11:18:33,2026-04-06 11:18:33

In [6]:
prettify(transactions_df.head())

,ID,client_id,platform_id,asset_id,status_id,Date,Amount,Buy Price,currency_id,Buy Price (EUR),Exchange Fee,Service Fee,Referral Bonus,transaction_type,created_at,updated_at
0,1,1,1,1,2,2025-01-10,0.05,42000.0,1,38640.0,10.0,5.0,0.0,BUY,2026-04-06 11:17:29,2026-04-06 11:17:29
1,2,2,2,1,2,2025-02-15,0.02,45000.0,1,41850.0,8.0,4.0,0.0,BUY,2026-04-06 11:17:29,2026-04-06 11:17:29
2,3,3,3,1,2,2025-03-01,0.01,47000.0,1,42770.0,7.0,3.0,1.0,BUY,2026-04-06 11:17:29,2026-04-06 11:17:29
3,4,4,1,2,2,2025-03-10,1.20,2500.0,1,2350.0,5.0,2.0,0.0,BUY,2026-04-06 11:17:29,2026-04-06 11:17:29
4,5,5,2,2,2,2025-04-01,0.80,2600.0,1,2392.0,6.0,3.0,2.0,BUY,2026-04-06 11:17:29,2026-04-06 11:17:29

In [13]:
len(transactions_df)

223

In [14]:
len(market_prices_df)

732

In [15]:
market_prices_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 732 entries, 0 to 731
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   price_id    732 non-null    int64
 1   asset_id    732 non-null    int64
 2   price_date  732 non-null    datetime64[us]
 3   price_usd   732 non-null    float64
 4   eur_rate    732 non-null    float64
 5   price_eur   732 non-null    float64
 6   created_at  732 non-null    datetime64[us]
 7   updated_at  732 non-null    datetime64[us]
dtypes: datetime64[us](3), float64(3), int64(2)
memory usage: 45.9 KB

In [16]:
market_prices_df["price_date"].min()

Timestamp('2025-04-10 00:00:00')

In [17]:
market_prices_df["price_date"].max(),market_prices_df["price_date"].min(),

(Timestamp('2026-04-08 07:09:23'), Timestamp('2025-04-10 00:00:00'))

In [119]:
print("MIN: ", market_prices_df["price_date"].min())
print("MAX: ", market_prices_df["price_date"].max())

MIN:  2025-04-10 00:00:00
MAX:  2026-03-31 00:00:00

In [120]:
market_prices_df["price_date"] = pd.to_datetime(market_prices_df["price_date"]) #datetime format

In [121]:
market_prices_df["price_date"] = market_prices_df["price_date"].dt.strftime("%Y-%m-%d") #string format

In [122]:
market_prices_df.isnull().sum()

price_id      0
asset_id      0
price_date    0
price_eur     0
created_at    0
updated_at    0
price_usd     0
eur_rate      0
dtype: int64

In [123]:
transactions_df.isnull().sum()

transaction_id        0
client_id             0
platform_id           0
asset_id              0
status_id             0
transaction_date      0
amount                0
buy_price             0
currency_id           0
buy_price_eur         0
exchange_fee_eur      0
service_fee_eur       0
referral_bonus_eur    0
created_at            0
updated_at            0
transaction_type      0
dtype: int64

In [124]:
market_prices_df["asset_id"].nunique()

2

In [125]:
transactions_df["asset_id"].nunique()

2

In [126]:
query= """
SELECT
    COUNT(*) AS total_rows,
    SUM(price_usd IS NULL) AS price_usd_nulls,
    SUM(price_eur IS NULL) AS price_eur_nulls,
    SUM(eur_rate IS NULL) AS eur_rate_nulls
FROM market_prices;
"""


df_check = pd.read_sql(query, connection)
df_check

   total_rows  price_usd_nulls  price_eur_nulls  eur_rate_nulls
0         712              0.0              0.0             0.0

In [127]:
df_check2=pd.DataFrame({
    "total_rows": [len(market_prices_df)],
    "price_usd_nulls":[market_prices_df["price_usd"].isna().sum()],
    "price_eur_nulls":[market_prices_df["price_eur"].isna().sum()],
    "eur_rate_nulls":[market_prices_df["eur_rate"].isna().sum()]
})
df_check2

   total_rows  price_usd_nulls  price_eur_nulls  eur_rate_nulls
0         712                0                0               0

In [128]:
query="""
SELECT
    mp.price_date,
    mp.price_eur
FROM market_prices mp
JOIN assets a ON mp.asset_id = a.asset_id
WHERE a.asset_symbol='BTC'
ORDER BY mp.price_date;
"""

btc_df = pd.read_sql(query, connection)
btc_df.head()

  price_date     price_eur
0 2025-04-10  74554.941588
1 2025-04-11  70153.841453
2 2025-04-12  73540.885424
3 2025-04-13  75185.353593
4 2025-04-14  73482.612844

In [129]:
# перетворюємо дату (важливо для графіка!)
btc_df["price_date"] = pd.to_datetime(btc_df["price_date"])

In [2]:
#graffik - Ich verwende matplotlib für die Visualisierung der Daten
import matplotlib.pyplot as plt

plt.figure()

plt.plot(btc_df["price_date"], btc_df["price_eur"])

plt.title("Bitcoin Price Trend (EUR)")
plt.xlabel("Date")
plt.ylabel("Price (EUR)")

plt.show()

NameError: name 'btc_df' is not defined

In [1]:
plt.figure()

#період
btc_df= btc_df[
    (btc_df["price_date"]>="2025-10-01")&
    (btc_df["price_date"]<="2026-04-01")
]

#*середнє значення ціни за останні 40 і 7 днів
btc_df["rolling_avg_40"]=btc_df["price_eur"].rolling(window=40, min_periods=1).mean()
btc_df["rolling_avg_7"]=btc_df["price_eur"].rolling(window=7).mean()

# реальна ціна
plt.plot(btc_df["price_date"], btc_df["price_eur"], label="Price")
# тренд (rolling avg)
plt.plot(btc_df["price_date"], btc_df["rolling_avg_40"], label="Trend (40 days)")
plt.plot(btc_df["price_date"], btc_df["rolling_avg_7"], label="Trend (7 days)")

plt.title("Bitcoin Price Trend (EUR)")
plt.xlabel("Date")
plt.ylabel("Price (EUR)")

plt.legend()
plt.grid()
plt.xticks(rotation=45)

plt.show()

#Ein 40-Tage-Durchschnitt zeigt den langfristigen Trend,
# während ein 7-Tage-Durchschnitt kurzfristige Schwankungen zeigt
# Der gleitende Durchschnitt beginnt erst nach 40 Tagen, weil vorher nicht genügend Daten vorhanden sind.

NameError: name 'plt' is not defined

In [134]:
cursor = connection.cursor()
cursor.execute("DROP VIEW IF EXISTS v_transactions_overview;")
cursor.close()
print("View deleted")
connection.close()

View deleted